require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Rails/BulkChangeTable:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

RSpec/ExampleLength:
  Max: 24

RSpec/MultipleExpectations:
  Enabled: false
